# AUTHOR: D YOAN L MEKONTCHOU YOMBA - Kurt Schmidt
# Date: January 12, 2018
PYTHON = python
VIEWER = less

.PHONY:run view
run : hello.py
	chmod u+x hello.py 
	$(PYTHON) hello.py

view : hello.py
	$(VIEWER) hello.py 

